### ISSUE TITLE
Purpose of Suppress("LeakingThis")

### ISSUE THREAD

**Issue by IgorGanapolsky** [KucherenkoIhor/ExploringViewModel#1]
Hello,
in your BaseLifecycleActivity, you have an annotation:
`@Suppress("LeakingThis")`

Can you briefly explain the purpose of this annotation?  It doesn't have effect on Lint, since nothing similar causes a warning.

Thank you for the sample,
Igor

**Comment by KucherenkoIhor** [comment]
@IgorGanapolsky Thank you.
Yes, of course. 
BaseLifecycleActivity contains this line: private val registry = LifecycleRegistry(this). Here we pass activity instance to another class. And it can be the reason of memory links. I use this annotation to show that I aware this. (to other developers and lint). Did I answer on your question?

**Comment by IgorGanapolsky** [comment]
@KucherenkoIhor I get it now, thanks.  I just don't see Lint as caring about this unless you define your own custom Lint rules?

**Comment by KucherenkoIhor** [comment]
@IgorGanapolsky no, just default settings.
