### ISSUE TITLE
Kotlin-android vs findViewById

### ISSUE THREAD

**Issue by IgorGanapolsky** [KucherenkoIhor/ExploringViewModel#2]
Hi,
I'm getting up to speed in Kotlin.  I know there is https://kotlinlang.org/docs/tutorials/android-plugin.html - which let you avoid writing **findViewById** calls.  I'd like to know - is there a reason you are using `findViewById` in this code?  I see you are declaring them as `lazy`, but cannot see the advantage to them...

Thank you,
Igor

**Comment by KucherenkoIhor** [comment]
Yes, you can use extensions plugin and refer to view instance by its id. But it's just small sample. So, I decided not to use the plugin. The that you can write findViewById in one line with definition of reference to view is the advantage of lazy. You can read more about it here:“Delegation in Kotlin” https://medium.com/proandroiddev/delegation-in-kotlin-e1efb849641
